# blocks: List of blocks (from Material enum) that are to be monitored
# amount: Number of blocks that must be broken before a notification is sent
# reminder: Another message will be sent every time this many blocks are broken past amount
# time: Time in seconds before the counter resets

# notifyMessage: Message sent to players with blockmonitor.notify and the console when too many monitored blocks are placed.
# Replacers:
# %PLAYER%: The player's name
# %NUMBER%: The number of blocks placed
# %BLOCK%: The block being broken
# %TIME%: The value of cooldownTime
# %LOCATION%: The location of the block placed
# locationFormat: The format of the text replaced by %LOCATION%
# Replacers:
# %WORLD%: The world name
# %XCoord%: The X coordinate
# %YCoord%: The Y coordinate
# %ZCoord%: The Z coordinate


notifyMessage: "&7[&cXRayDetector&7] &4%PLAYER% has broken %NUMBER% %BLOCK% in the past %TIME% seconds. Most recent at %LOCATION%"
locationFormat: "World: %WORLD%, X: %XCoord%, Y: %YCoord%, Z: %ZCoord%"

blocks:
  DIAMOND_ORE:
    amount: 10
    reminder: 5
    time: 120
  EMERALD_ORE:
    amount: 5
    reminder: 2
    time: 60
  ANCIENT_DEBRIS:
    amount: 5
    reminder: 1
    time: 300
