name: XRayDetector
author: RoboticPlayer
version: 1.1
main: io.github.ryanehenderson.xraydetector.XRayDetector
api-version: 1.16

permissions:
  xraydetector.*:
    description: All xraydetector permissions
    children:
      xraydetector.bypass: true
      xraydetector.notify: true
  xraydetector.bypass:
    description: Bypass xraydetector checks
  xraydetector.notify:
    description: Be notified of potential cheaters
